# Set up a JupyterHub that incldues all CSDMS Workbench software.
FROM quay.io/jupyter/scipy-notebook

LABEL maintainer="CSDMS <csdms@colorado.edu>"
LABEL author="Mark Piper"
LABEL email="mark.piper@colorado.edu"
