#! /usr/bin/env bash
#
# Print the usernames of people logged into the Hub.
#
systemctl list-units | grep jupyterhub-singleuser | awk -F".service" '/service/{print $1}' | awk -F"jupyter-" '/jupyter/{print $2}'
exit 0
