#!/usr/bin/env zsh
# Set up the Google Cloud SDK environment.
#
# Use:
#   source activate_gcloud

GOOGLE_CLOUD_SDK_DIR=${HOME}/Applications/google-cloud-sdk

if [ -f ${GOOGLE_CLOUD_SDK_DIR}/path.zsh.inc ]; then
    . ${GOOGLE_CLOUD_SDK_DIR}/path.zsh.inc;
fi
if [ -f ${GOOGLE_CLOUD_SDK_DIR}/completion.zsh.inc ]; then
    . ${GOOGLE_CLOUD_SDK_DIR}/completion.zsh.inc;
fi
