#!/usr/bin/env zsh
# Set up the Google Cloud SDK environment.
#
# Use:
#   source activate_gcloud

CLOUDSDK_DIR=${HOME}/Applications/google-cloud-sdk
export CLOUDSDK_PYTHON=${HOME}/anaconda3/bin/python

if [ -f ${CLOUDSDK_DIR}/path.zsh.inc ]; then
    . ${CLOUDSDK_DIR}/path.zsh.inc;
    PS1="[gke] $PS1"
fi
if [ -f ${CLOUDSDK_DIR}/completion.zsh.inc ]; then
    . ${CLOUDSDK_DIR}/completion.zsh.inc;
fi
