# An eksctl ClusterConfig example.
---
kind: ClusterConfig
apiVersion: eksctl.io/v1alpha5

metadata:
  name: csdms-demo-1
  region: us-west-1
   version: 1.29

managedNodeGroups:
  - name: ng-1
    instanceType: t3a.medium
    desiredCapacity: 2
    minSize: 2
    maxSize: 4
    volumeSize: 20
    volumeType: gp2
    availabilityZones: ["us-west-1a", "us-west-1b"]
