# A conda environment for building GRASS GIS from source.

name: grass
channels:
  - conda-forge
dependencies:
  - pip
  - python =3
  - bison
  - bz2file
  - c-compiler
  - cxx-compiler
  - cairo
  - fftw
  - flex
  - freetype
  - gdal
  - geos
  - gettext
  - make
  - pdal
  - pkg-config
  - proj
  - readline
  - zstd
  # - libpng-devel-cos7-x86_64
